services:
  backend:
    build: ./backend
    image: smart-recruitment-backend:latest
    restart: unless-stopped
    command: sh entrypoint.sh
    env_file:
      - .env.prod
    environment:
      PYTHONUNBUFFERED: 1

  celery:
    image: smart-recruitment-backend:latest
    container_name: celery_worker
    restart: unless-stopped
    command: celery -A core worker -l info -Q resume_parsing --concurrency=2 --without-gossip --without-mingle
    env_file:
      - .env.prod
    environment:
      PYTHONUNBUFFERED: 1

  celery_email:
    image: smart-recruitment-backend:latest
    container_name: celery_email_worker
    restart: unless-stopped
    command: celery -A core worker -l info -Q email_service --concurrency=2 --without-gossip --without-mingle
    env_file:
      - .env.prod
    environment:
      PYTHONUNBUFFERED: 1

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "while :; do
      certbot renew;
      sleep 12h;
      done"
