# Generated by Django 4.2.28 on 2026-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
