# Generated by Django 4.2.28 on 2026-03-18 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
        ("jobs", "0002_remove_jobapplication_resume_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="ai_score",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="parsed_data",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="resume_file",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications_resume",
                to="resumes.resume",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("reviewing", "Reviewing"),
                    ("shortlisted", "Shortlisted"),
                    ("rejected", "Rejected"),
                    ("hired", "Hired"),
                ],
                default="reviewing",
                max_length=20,
            ),
        ),
    ]
