from django.db import migrations


def delete_and_reseed_skills(apps, schema_editor):
    Skill = apps.get_model("jobs", "Skill")
    Category = apps.get_model("jobs", "Category")

    # Delete all existing skills
    Skill.objects.all().delete()

    # Create/Get categories first
    categories = {}
    category_names = [
        "Programming Languages",
        "Web Development",
        "Backend Development",
        "Databases",
        "Cloud & DevOps",
        "AI / ML / Data Science",
        "Blockchain / Web3",
        "Mobile Development",
        "Testing",
        "Security",
        "Data / Analytics / BI",
        "Soft Skills",
        "Tools & Platforms",
    ]

    for cat_name in category_names:
        cat, _ = Category.objects.get_or_create(name=cat_name)
        categories[cat_name] = cat

    # Skill data with aliases
    category_skills = {
        "Programming Languages": {
            "Python": [],
            "Java": [],
            "JavaScript": ["JS"],
            "TypeScript": ["TS"],
            "C": [],
            "C++": ["CPP", "C Plus Plus"],
            "C#": ["CSharp", "C Sharp"],
            "Go": ["Golang"],
            "Rust": [],
            "Kotlin": [],
            "Swift": [],
            "Ruby": [],
            "PHP": [],
            "Scala": [],
            "Dart": [],
            "Objective-C": ["Objective C"],
            "MATLAB": [],
            "R": [],
            "Julia": [],
            "Groovy": [],
            "Bash": ["Shell"],
            "Shell Scripting": ["Bash"],
            "Assembly": [],
            "COBOL": [],
            "Fortran": [],
            "Elixir": [],
            "Haskell": [],
            "F#": ["FSharp", "F Sharp"],
            "Nim": [],
            "Zig": [],
        },
        "Web Development": {
            "HTML": [],
            "CSS": [],
            "SASS": ["SCSS"],
            "LESS": [],
            "Tailwind CSS": ["Tailwind"],
            "Bootstrap": [],
            "Material UI": ["MUI"],
            "Chakra UI": ["Chakra"],
            "React": ["ReactJS", "React.js"],
            "Next.js": ["Nextjs", "Next"],
            "Vue.js": ["Vuejs", "Vue"],
            "Nuxt.js": ["Nuxtjs", "Nuxt"],
            "Angular": ["AngularJS"],
            "Svelte": [],
            "Redux": [],
            "Zustand": [],
            "jQuery": ["JQuery"],
            "Webpack": [],
            "Vite": [],
            "Parcel": [],
            "Babel": [],
            "Three.js": ["Threejs", "Three"],
            "WebGL": [],
        },
        "Backend Development": {
            "Django": [],
            "Flask": [],
            "FastAPI": ["Fast API"],
            "Node.js": ["NodeJS", "Node JS", "nodejs", "Nodejs"],
            "Express.js": ["Expressjs", "Express"],
            "NestJS": ["Nestjs", "Nest"],
            "Spring Boot": ["SpringBoot"],
            "Ruby on Rails": ["Rails"],
            "Laravel": [],
            "ASP.NET": ["AspNET", "ASP Net"],
            "GraphQL": [],
            "REST API": ["REST", "RESTful"],
            "gRPC": [],
            "Microservices": [],
            "Serverless": [],
            "JWT Authentication": ["JWT"],
            "OAuth": [],
        },
        "Databases": {
            "PostgreSQL": ["Postgres", "SQL"],
            "MySQL": [],
            "SQLite": [],
            "MongoDB": ["NoSQL"],
            "Redis": [],
            "Cassandra": [],
            "DynamoDB": [],
            "Firebase": [],
            "Supabase": [],
            "CockroachDB": ["CockroachDB"],
            "MariaDB": [],
            "Oracle DB": ["Oracle"],
            "Neo4j": [],
            "ElasticSearch": ["Elasticsearch"],
            "TimescaleDB": [],
        },
        "Cloud & DevOps": {
            "AWS": ["Amazon Web Services"],
            "Azure": ["Microsoft Azure"],
            "Google Cloud": ["GCP", "Google Cloud Platform"],
            "Docker": [],
            "Kubernetes": ["K8s", "K8"],
            "Helm": [],
            "Terraform": [],
            "Ansible": [],
            "Jenkins": [],
            "GitHub Actions": [],
            "GitLab CI/CD": ["GitLab CI"],
            "CircleCI": ["Circle CI"],
            "Prometheus": [],
            "Grafana": [],
            "Nginx": ["NGINX"],
            "Apache": [],
            "Linux": [],
            "Ubuntu": [],
            "Debian": [],
            "Load Balancing": [],
            "Auto Scaling": [],
        },
        "AI / ML / Data Science": {
            "Machine Learning": ["ML"],
            "Deep Learning": ["DL"],
            "NLP": ["Natural Language Processing"],
            "Computer Vision": ["CV"],
            "TensorFlow": [],
            "PyTorch": ["Pytorch"],
            "Keras": [],
            "Scikit-learn": ["Sklearn", "Scikit learn"],
            "Pandas": [],
            "NumPy": ["Numpy"],
            "Matplotlib": [],
            "Seaborn": [],
            "OpenCV": [],
            "spaCy": ["Spacy"],
            "NLTK": [],
            "Transformers": ["Hugging Face Transformers"],
            "Hugging Face": [],
            "LLMs": ["Large Language Models"],
            "LangChain": ["Langchain"],
            "Data Analysis": [],
            "Feature Engineering": [],
            "Model Deployment": [],
            "MLOps": [],
        },
        "Blockchain / Web3": {
            "Solidity": [],
            "Ethereum": ["Web3"],
            "Smart Contracts": [],
            "Web3.js": ["Web3js"],
            "Ethers.js": ["Ethersjs", "Ethers"],
            "Hardhat": [],
            "Foundry": [],
            "IPFS": [],
            "Polygon": [],
            "DeFi": ["Decentralized Finance"],
            "NFT Development": ["NFT"],
        },
        "Mobile Development": {
            "Android": [],
            "iOS": ["iPhone"],
            "React Native": ["React Native"],
            "Flutter": [],
            "SwiftUI": [],
            "Kotlin Multiplatform": ["KMP"],
            "Expo": [],
            "Xamarin": [],
        },
        "Testing": {
            "Unit Testing": [],
            "Integration Testing": [],
            "E2E Testing": ["E2E", "End to End Testing"],
            "Jest": [],
            "Mocha": [],
            "Chai": [],
            "PyTest": ["Pytest"],
            "JUnit": [],
            "Selenium": [],
            "Cypress": [],
            "Playwright": [],
            "TestNG": [],
        },
        "Security": {
            "Cybersecurity": [],
            "Ethical Hacking": [],
            "Penetration Testing": ["Pen Testing", "PenTesting"],
            "OWASP": [],
            "Encryption": [],
            "SSL/TLS": ["SSL", "TLS"],
            "Network Security": [],
            "IAM": [],
        },
        "Data / Analytics / BI": {
            "SQL": [],
            "Data Warehousing": [],
            "ETL": [],
            "Apache Spark": ["Spark"],
            "Hadoop": [],
            "Airflow": ["Apache Airflow"],
            "Power BI": ["PowerBI"],
            "Tableau": [],
            "Looker": [],
            "BigQuery": [],
            "Snowflake": [],
        },
        "Soft Skills": {
            "Problem Solving": [],
            "Communication": [],
            "Leadership": [],
            "Teamwork": [],
            "Time Management": [],
            "Critical Thinking": [],
            "Adaptability": [],
            "Creativity": [],
            "Decision Making": [],
            "Conflict Resolution": [],
        },
        "Tools & Platforms": {
            "Git": [],
            "GitHub": [],
            "GitLab": [],
            "Bitbucket": [],
            "Postman": [],
            "Figma": [],
            "Jira": [],
            "Notion": [],
            "Slack": [],
            "VS Code": ["VSCode", "Visual Studio Code"],
            "IntelliJ": [],
            "PyCharm": [],
            "Docker Compose": ["Docker-Compose"],
            "ngrok": [],
        },
    }

    # Create skills with aliases
    for category_name, skills_dict in category_skills.items():
        category = categories[category_name]
        for skill_name, aliases in skills_dict.items():
            Skill.objects.create(
                name=skill_name,
                category=category,
                aliases=aliases,
            )


def reverse_reseed(apps, schema_editor):
    # Keep data on reverse to avoid removing recruiter-managed skill records
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_category_skill_aliases"),
    ]

    operations = [
        migrations.RunPython(delete_and_reseed_skills, reverse_reseed),
    ]
