# Generated by Django 4.2.28 on 2026-03-20

from django.core import validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_merge_0007_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications_resume",
                to="resumes.resume",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="score",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[validators.MinValueValidator(0.0), validators.MaxValueValidator(1.0)],
            ),
        ),
    ]
