# Generated by Django 4.2.28 on 2026-03-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_enforce_user_fk_cascades"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobQuestions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
