# Generated by Django 4.2.28 on 2026-04-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0015_jobapplication_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijobdraftrequest",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
