# Generated by Django 4.2.28 on 2026-03-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("FAILED", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
