# Generated by Django 4.2.28 on 2026-03-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_alter_resume_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="parsed_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
