# Generated by Django 4.2.28 on 2026-03-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_resume_parsed_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="skills",
        ),
    ]
