# Generated by Django 4.2.28 on 2026-03-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_remove_resume_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="score",
        ),
    ]
