# Generated by Django 4.2.28 on 2026-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_merge_0007_branches"),
        ("users", "0003_user_profile_builder_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="preferred_role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="skills",
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="skilled_users", to="jobs.skill"
            ),
        ),
    ]
