# Generated by Django 4.2.28 on 2026-03-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_preferred_role_remove_user_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="education",
        ),
        migrations.RemoveField(
            model_name="user",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="user",
            name="links",
        ),
        migrations.RemoveField(
            model_name="user",
            name="projects",
        ),
    ]
