# Generated by Django 4.2.28 on 2026-03-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_education_remove_user_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="primary_resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_for_users",
                to="resumes.resume",
            ),
        ),
    ]
